import{i as a,S as u}from"./assets/vendor-5b791d57.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();function p(i){const s="https://pixabay.com/",t="api/",o=new URLSearchParams({key:"43016560-45bd583880e427992fd0250d3",q:i,image_type:"photo",orientation:"horizontal",safesearch:!0}),e=`${s}${t}?${o}`;return fetch(e).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()})}function m(i){return i.length===0?(a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",theme:"dark"}),""):i.map(t=>`<li class="pictures-list-item">
        <a class="picture-link" href="${t.largeImageURL}">
        <img src="${t.webformatURL}" alt="${t.tags}" class="picture" />
        </a>
        <ul class="picture-data-list">
          <li class="picture-data-item"><p class="picture-inf">Likes</p><p class = "picture-inf-number">${t.likes}</p></li>
          <li class="picture-data-item"><p class="picture-inf">Views</p><p class = "picture-inf-number">${t.views}</p></li>
          <li class="picture-data-item"><p class="picture-inf">Comments</p><p class = "picture-inf-number">${t.comments}</p></li>
          <li class="picture-data-item"><p class="picture-inf">Downloads</p><p class = "picture-inf-number">${t.downloads}</p></li>
        </ul>
      </li>`).join("")}const l=document.querySelector(".search-photo"),n=document.querySelector(".pictures-list"),f=new u(".pictures-list a",{captionsData:"alt",captionDelay:250});l.addEventListener("submit",d);function d(i){i.preventDefault(),n.innerHTML="";const s=l.search.value.toLowerCase().trim();s!=""?p(s).then(t=>{const o=t.hits;console.log(o),n.innerHTML=m(o),f.refresh()}).catch(t=>console.log(t)):a.error({message:"Please enter valid query.",position:"topRight",theme:"dark"})}
//# sourceMappingURL=commonHelpers.js.map
